# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/temp.xdc

# IP: ip/bram_A/bram_A.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_A || ORIG_REF_NAME==bram_A} -quiet] -quiet

# IP: ip/bram_B/bram_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_B || ORIG_REF_NAME==bram_B} -quiet] -quiet

# IP: ip/bram_C/bram_C.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_C || ORIG_REF_NAME==bram_C} -quiet] -quiet

# XDC: c:/Users/kpcha/Desktop/College/DSD/Ver2_6/Ver2_6.gen/sources_1/ip/bram_A/bram_A_ooc.xdc

# XDC: c:/Users/kpcha/Desktop/College/DSD/Ver2_6/Ver2_6.gen/sources_1/ip/bram_B/bram_B_ooc.xdc

# XDC: c:/Users/kpcha/Desktop/College/DSD/Ver2_6/Ver2_6.gen/sources_1/ip/bram_C/bram_C_ooc.xdc
